#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Run tests when committing to master.
if [[ $refname = "refs/heads/master" ]] ; then
  ruby test_* > /dev/null
  # $? is a shell variable which stores the return code from what we just ran
  rc=$?
  if [[ $rc != 0 ]] ; then
    # A non-zero return code means an error occurred, so tell the user and exit
    echo "Ruby tests failed on $newrev - commit denied. Run tests locall and try again."
    exit $rc
  fi
fi
